In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1,2,3], [4,5,6,], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexado

In [6]:
arr[0] + arr[1]

3

In [7]:
matriz[0] #Primera fila 

array([1, 2, 3])

In [8]:
matriz[0,2] #Pimer fila, tercer columna 

3

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[0:3] #Start incluido, stop no incluido 

array([1, 2, 3])

In [11]:
arr[::3] #De tres en tres 

array([1, 4, 7])

In [12]:
arr[-1] #El último valor, se puede indexar negativamente 

9

In [13]:
matriz[1:] #Desde la segunda hacía adelante 

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[1:, 0:2] # A nivel de filas de la uno hacía adelante, a nivel de columnas las primeras dos

array([[4, 5],
       [7, 8]])

## Tipos de datos de Numpy 

En numpy todo el array debe estar definido sobre el mismo tipo de dato 

In [15]:
arr = np.array([1,2,3,4])
arr.dtype #Para ver que tipo de datos tiene el array. 

dtype('int64')

In [16]:
#Definir el tipo de datos 
arr2 = np.array([1,2,3,4], dtype='float64')
arr2.dtype

dtype('float64')

In [17]:
#Si quiero cambiar un tipo de dato ya definido 
arr = arr.astype(np.float64)
arr.dtype

dtype('float64')

In [18]:
arr3 = np.array([0,1,2,3,4], dtype='bool') #0 es falso todo lo demás es verdadero 
arr3

array([False,  True,  True,  True,  True])